import { Member } from './member';

export const MEMBERS: Member[] = [
    { id: 11, name: 'Bojan', surname: 'Siljanoski',age:22,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123}
    ,{ id: 12, name: 'Sara',surname: 'Mojsova',age:22,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123} 
    ,{ id: 13, name: 'Stefan',surname: 'Minchevski',age:27,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 14, name: 'Ljubica',surname: 'Boneva',age:24,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 15, name: 'Sanja',surname: 'Puskarova',age:24,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 16, name: 'Ilija',surname: 'Jolevski',age:40,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 17, name: 'Ana',surname: 'Petkova',age:30,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 18, name: 'Andrej', surname: 'Siljanoski',age:19,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 19, name: 'Zvonko', surname: 'Zvonkoski',age:43,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, }
    ,{ id: 20, name: 'Petar', surname: 'Petrushevski',age:51,phone:123,
    email:'proba@yahoo.com',
    gender:'asd',
    language:'macedonian',
    occupation:'dasd',
    company:'Inellipse',
    username:'asd123',
    password:123, 
    }
  ];