import { Member } from './member';

export const MEMBERS: Member[] = [
    { id: 11, name: 'Bojan', surname: 'Siljanoski',age:22,phone:123,
    email:'proba@yahoo.com',
    gender:'Male',
    language:'Macedonian',
    occupation:'Student',
    company:'Inellipse',
    username:'boki22',
    password:812384}
    ,{ id: 12, name: 'Sara',surname: 'Mojsova',age:22,phone:123,
    email:'proba@yahoo.com',
    gender:'Female',
    language:'Macedonian',
    occupation:'Student',
    company:'Inellipse',
    username:'saram12',
    password:727127} 
    ,{ id: 13, name: 'Stefan',surname: 'Minchevski',age:27,phone:123,
    email:'proba@yahoo.com',
    gender:'Male',
    language:'Macedonian',
    occupation:'Intern',
    company:'Inellipse',
    username:'mstefan12',
    password:38124812, }
    ,{ id: 14, name: 'Ljubica',surname: 'Boneva',age:24,phone:123,
    email:'proba@yahoo.com',
    gender:'Female',
    language:'Macedonian',
    occupation:'Intern',
    company:'Inellipse',
    username:'bonevalj',
    password:2138412, }
    ,{ id: 15, name: 'Sanja',surname: 'Puskarova',age:24,phone:123,
    email:'proba@yahoo.com',
    gender:'Female',
    language:'Macedonian',
    occupation:'Intern',
    company:'Inellipse',
    username:'puskarovas2',
    password:123892184, }
    ,{ id: 16, name: 'Ilija',surname: 'Jolevski',age:40,phone:123,
    email:'proba@yahoo.com',
    gender:'Male',
    language:'Macedonian',
    occupation:'Owner',
    company:'Inellipse',
    username:'jolevskii',
    password:42184182, }
    ,{ id: 17, name: 'Ana',surname: 'Petkova',age:30,phone:123,
    email:'proba@yahoo.com',
    gender:'Female',
    language:'Macedonian',
    occupation:'Student',
    company:'Inellipse',
    username:'anapet',
    password:291492, }
    ,{ id: 18, name: 'Andrej', surname: 'Siljanoski',age:19,phone:123,
    email:'proba@yahoo.com',
    gender:'Male',
    language:'Macedonian',
    occupation:'Student',
    company:'Inellipse',
    username:'andrejs',
    password:213942, }
    ,{ id: 19, name: 'Zvonko', surname: 'Zvonkoski',age:43,phone:123,
    email:'proba@yahoo.com',
    gender:'Male',
    language:'Macedonian',
    occupation:'Team Leader',
    company:'Inellipse',
    username:'zvonkoz',
    password:2349232, }
    ,{ id: 20, name: 'Petar', surname: 'Petrushevski',age:51,phone:123,
    email:'proba@yahoo.com',
    gender:'Male',
    language:'Macedonian',
    occupation:'Student',
    company:'Inellipse',
    username:'petarp',
    password:997722, 
    }
  ];